# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-12 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableWxPublicPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=128)),
                ('buyInfo', models.CharField(max_length=4096)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
